### ISSUE TITLE
Как его запустить ?

### ISSUE THREAD

**Issue by Noneeer** [hdk5-archive/cosinus#1]
Выдает ошибку, что делать с VK_BOT_MAILBOXES ?

```
PS C:\Users\Leeen\Desktop\cosinus-arctg> python run.py
Traceback (most recent call last):
  File "run.py", line 5, in <module>
    from bot_config import config
  File "C:\Users\Leeen\Desktop\cosinus-arctg\bot_config.py", line 17, in <module>
    "mailboxes": eval(os.environ.get("VK_BOT_MAILBOXES"))
TypeError: eval() arg 1 must be a string, bytes or code object
```

**Comment by hdk5** [comment]
А это хороший вопрос!
Краткий ответ: а не нужно его запускать!
Грубо говоря, это личный проект двух с половиной человек без какой-либо документации. То есть, этим кодом пользуется тот и только тот, кто сам его пишет и как-то понимает.

И всё же, в данном случае ожидается, что в env-var VK_BOT_MAILBOXES будет чистой строкой написан питоновский словарь вида
```py
{
    chatnum: {
        'server': 'imap.mailserver', 
        'credentials': ('login', 'password'), 
        'page': 'http://mail.loginpage/'}
    }
}
```
дабы в соответствующую беседу приходили уведомления о новых письмах с почты.
